---

- name: apt | observium dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-mysql
    - php5-gd
    - php5-mcrypt
    - php5-json
    - php-pear
    - snmp
    - fping
    - mysql-server
    - mysql-client
    - python-mysqldb
    - rrdtool
    - subversion
    - whois
    - mtr-tiny
    - ipmitool
    - graphviz
    - imagemagick

- set_fact:
    nginx_conf: /etc/nginx/sites-available
    supervisor_confdir: /etc/supervisor/conf.d
    supervisor_targetconf: mig.conf
    supervisor_service: supervisor
    cron_svc: cron

- name: Check apache listening interface - ports.conf
  lineinfile: dest=/etc/apache2/ports.conf line="Listen {{ observium_vhostport }}" backup=yes
  notify:
    - restart apache
