---

- name: apt | observium dependencies
  apt: name={{ observium_pkg }} state=present update_cache=yes

- name: debian | Ensure Mysql is running and enabled on boot.
  service: name=mysql state=started enabled=yes

- name: Check apache listening interface - ports.conf
  lineinfile: dest=/etc/apache2/ports.conf line="Listen {{ observium_vhostport }}" backup=yes
  notify:
    - restart apache
