---

- name: yum | observium dependencies install
  yum: name={{ observium_pkg }} state=present update_cache=yes

- name: Redhat | Ensure cron is running and enabled on boot.
  service: name="{{ cron_svc }}" state=started enabled=yes
- name: Redhat | Ensure Mysql/Mariadb is running and enabled on boot.
  service: name=mariadb state=started enabled=yes
- name: Redhat | Ensure HTTPD is running and enabled on boot.
  service: name=httpd state=started enabled=yes

- name: disable selinux (observium recommendation...)
  selinux: state=disabled

- name: Check apache listening interface
#  lineinfile: dest=/etc/httpd/conf/httpd.conf line="Listen {{ observium_vhostport }}" follow=yes validate='/usr/sbin/apache2ctl -f %s -t' backup=yes insertafter="^Listen 80"
  lineinfile: dest=/etc/httpd/conf/httpd.conf line="Listen {{ observium_vhostport }}" follow=yes backup=yes insertafter="^Listen 80"
  notify:
    - restart apache
